# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = 'd7bb8b11990b8dc189a8a1144cec9155'
  config.secret_key = '715afe2c9f674fefbd11d73b9289c0d5'
  config.default_from = 'noreply@conference.upt.ro'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
