# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = 'f4c03a292b6d0e0c61baf7f58cc9d352'
  config.secret_key = 'e5f530be618e9f6eeb17162e5c1f8d09'
  config.default_from = 'no-reply@conference.upt.ro'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
